-- Strongbox
data.raw.item["aai-strongbox"].subgroup = "store-solid"
data.raw.item["aai-strongbox"].order = "d"
data.raw.item["aai-strongbox-passive-provider"].subgroup = "logistic-pasive"
data.raw.item["aai-strongbox-passive-provider"].order = "b"
data.raw.item["aai-strongbox-active-provider"].subgroup = "logistic-active"
data.raw.item["aai-strongbox-active-provider"].order = "b"
data.raw.item["aai-strongbox-buffer"].subgroup = "logistic-buffer"
data.raw.item["aai-strongbox-buffer"].order = "b"
data.raw.item["aai-strongbox-storage"].subgroup = "logistic-storage"
data.raw.item["aai-strongbox-storage"].order = "b"
data.raw.item["aai-strongbox-requester"].subgroup = "logistic-requester"
data.raw.item["aai-strongbox-requester"].order = "b"

-- Storehouse
data.raw.item["aai-storehouse"].subgroup = "store-solid"
data.raw.item["aai-storehouse"].order = "e"
data.raw.item["aai-storehouse-passive-provider"].subgroup = "logistic-pasive"
data.raw.item["aai-storehouse-passive-provider"].order = "c"
data.raw.item["aai-storehouse-active-provider"].subgroup = "logistic-active"
data.raw.item["aai-storehouse-active-provider"].order = "c"
data.raw.item["aai-storehouse-buffer"].subgroup = "logistic-buffer"
data.raw.item["aai-storehouse-buffer"].order = "c"
data.raw.item["aai-storehouse-storage"].subgroup = "logistic-storage"
data.raw.item["aai-storehouse-storage"].order = "c"
data.raw.item["aai-storehouse-requester"].subgroup = "logistic-requester"
data.raw.item["aai-storehouse-requester"].order = "c"

-- Warehouse
data.raw.item["aai-warehouse"].subgroup = "store-solid"
data.raw.item["aai-warehouse"].order = "f"
data.raw.item["aai-warehouse-passive-provider"].subgroup = "logistic-pasive"
data.raw.item["aai-warehouse-passive-provider"].order = "d"
data.raw.item["aai-warehouse-active-provider"].subgroup = "logistic-active"
data.raw.item["aai-warehouse-active-provider"].order = "d"
data.raw.item["aai-warehouse-buffer"].subgroup = "logistic-buffer"
data.raw.item["aai-warehouse-buffer"].order = "d"
data.raw.item["aai-warehouse-storage"].subgroup = "logistic-storage"
data.raw.item["aai-warehouse-storage"].order = "d"
data.raw.item["aai-warehouse-requester"].subgroup = "logistic-requester"
data.raw.item["aai-warehouse-requester"].order = "d"