-- Loaders
data.raw.item["5d-transport-belt-04-loader"].subgroup = "transport-dead-loader"
data.raw.item["5d-transport-belt-04-loader"].order = "d"
data.raw.item["5d-transport-belt-05-loader"].subgroup = "transport-dead-loader"
data.raw.item["5d-transport-belt-05-loader"].order = "e"
data.raw.item["5d-transport-belt-06-loader"].subgroup = "transport-dead-loader"
data.raw.item["5d-transport-belt-06-loader"].order = "f"
data.raw.item["5d-transport-belt-07-loader"].subgroup = "transport-dead-loader"
data.raw.item["5d-transport-belt-07-loader"].order = "g"
data.raw.item["5d-transport-belt-08-loader"].subgroup = "transport-dead-loader"
data.raw.item["5d-transport-belt-08-loader"].order = "h"

data.raw.recipe["5d-transport-belt-04-loader"].subgroup = "transport-dead-loader"
data.raw.recipe["5d-transport-belt-04-loader"].order = "d"
data.raw.recipe["5d-transport-belt-05-loader"].subgroup = "transport-dead-loader"
data.raw.recipe["5d-transport-belt-05-loader"].order = "e"
data.raw.recipe["5d-transport-belt-06-loader"].subgroup = "transport-dead-loader"
data.raw.recipe["5d-transport-belt-06-loader"].order = "f"
data.raw.recipe["5d-transport-belt-07-loader"].subgroup = "transport-dead-loader"
data.raw.recipe["5d-transport-belt-07-loader"].order = "g"
data.raw.recipe["5d-transport-belt-08-loader"].subgroup = "transport-dead-loader"
data.raw.recipe["5d-transport-belt-08-loader"].order = "h"

-- Beltbox
data.raw.item["5d-transport-belt-04-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.item["5d-transport-belt-04-beltbox"].order = "d"
data.raw.item["5d-transport-belt-05-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.item["5d-transport-belt-05-beltbox"].order = "e"
data.raw.item["5d-transport-belt-06-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.item["5d-transport-belt-06-beltbox"].order = "f"
data.raw.item["5d-transport-belt-07-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.item["5d-transport-belt-07-beltbox"].order = "g"
data.raw.item["5d-transport-belt-08-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.item["5d-transport-belt-08-beltbox"].order = "h"

data.raw.recipe["5d-transport-belt-04-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.recipe["5d-transport-belt-04-beltbox"].order = "d"
data.raw.recipe["5d-transport-belt-05-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.recipe["5d-transport-belt-05-beltbox"].order = "e"
data.raw.recipe["5d-transport-belt-06-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.recipe["5d-transport-belt-06-beltbox"].order = "f"
data.raw.recipe["5d-transport-belt-07-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.recipe["5d-transport-belt-07-beltbox"].order = "g"
data.raw.recipe["5d-transport-belt-08-beltbox"].subgroup = "transport-dead-beltbox"
data.raw.recipe["5d-transport-belt-08-beltbox"].order = "h"