-- Generated by mods/scripts/extract-tier-overlays.py -- do not edit by hand.
--
-- Maps each vanilla sprite layer to the per-tier recolour overlays that go
-- on top of it.  `match` is the layer's filename (or filenames[1]); the
-- `overlays` list mirrors that layer's own filenames list, so a multi-file
-- animation gets a multi-file overlay with the same geometry.
return {
    ["big-mining-drill"] = {
        {
            match = "__space-age__/graphics/entity/big-mining-drill/East/big-mining-drill-E-still-front.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/big-mining-drill/big-mining-drill-E-still-front-",
            },
        },
        {
            match = "__space-age__/graphics/entity/big-mining-drill/North/big-mining-drill-N-still.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/big-mining-drill/big-mining-drill-N-still-",
            },
        },
        {
            match = "__space-age__/graphics/entity/big-mining-drill/South/big-mining-drill-S-still-front.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/big-mining-drill/big-mining-drill-S-still-front-",
            },
        },
        {
            match = "__space-age__/graphics/entity/big-mining-drill/West/big-mining-drill-W-still-front.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/big-mining-drill/big-mining-drill-W-still-front-",
            },
        },
    },
    ["biochamber"] = {
        {
            match = "__space-age__/graphics/entity/biochamber/biochamber.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/biochamber/biochamber-",
            },
        },
    },
    ["biolab"] = {
        {
            match = "__space-age__/graphics/entity/biolab/biolab-anim.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/biolab/biolab-anim-",
            },
        },
    },
    ["crusher"] = {
        {
            match = "__space-age__/graphics/entity/crusher/crusher-horizontal.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/crusher/crusher-horizontal-",
            },
        },
        {
            match = "__space-age__/graphics/entity/crusher/crusher-vertical.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/crusher/crusher-vertical-",
            },
        },
    },
    ["electromagnetic-plant"] = {
        {
            match = "__space-age__/graphics/entity/electromagnetic-plant/electromagnetic-plant-main-cool-down.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/electromagnetic-plant/electromagnetic-plant-main-cool-down-",
            },
        },
        {
            match = "__space-age__/graphics/entity/electromagnetic-plant/electromagnetic-plant-main-rotate-1.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/electromagnetic-plant/electromagnetic-plant-main-rotate-1-",
                "__5dim_space_age__/graphics/tier-overlay/electromagnetic-plant/electromagnetic-plant-main-rotate-2-",
            },
        },
        {
            match = "__space-age__/graphics/entity/electromagnetic-plant/electromagnetic-plant-main-rotate-continue.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/electromagnetic-plant/electromagnetic-plant-main-rotate-continue-",
            },
        },
        {
            match = "__space-age__/graphics/entity/electromagnetic-plant/electromagnetic-plant-main-warm-up.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/electromagnetic-plant/electromagnetic-plant-main-warm-up-",
            },
        },
    },
    ["foundry"] = {
        {
            match = "__space-age__/graphics/entity/foundry/foundry-anim-1.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/foundry/foundry-main-1-",
                "__5dim_space_age__/graphics/tier-overlay/foundry/foundry-main-2-",
            },
        },
    },
    ["fusion-generator"] = {
        {
            match = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/fusion-generator/fusion-generator-east-",
            },
        },
        {
            match = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/fusion-generator/fusion-generator-north-",
            },
        },
        {
            match = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/fusion-generator/fusion-generator-south-",
            },
        },
        {
            match = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/fusion-generator/fusion-generator-west-",
            },
        },
    },
    ["fusion-reactor"] = {
        {
            match = "__space-age__/graphics/entity/fusion-reactor/fusion-reactor-main.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/fusion-reactor/fusion-reactor-main-",
            },
        },
    },
    ["lightning-collector"] = {
        {
            match = "__space-age__/graphics/entity/lightning-collector/lightning-collector.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/lightning-collector/lightning-collector-",
            },
        },
    },
    ["recycler"] = {
        {
            match = "__recycler__/graphics/entity/recycler/recycler-E.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/recycler/recycler-E-",
            },
        },
        {
            match = "__recycler__/graphics/entity/recycler/recycler-N.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/recycler/recycler-N-",
            },
        },
        {
            match = "__recycler__/graphics/entity/recycler/recycler-S.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/recycler/recycler-S-",
            },
        },
        {
            match = "__recycler__/graphics/entity/recycler/recycler-W.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/recycler/recycler-W-",
            },
        },
        {
            match = "__recycler__/graphics/entity/recycler/recycler-flipped-E.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/recycler/recycler-flipped-E-",
            },
        },
        {
            match = "__recycler__/graphics/entity/recycler/recycler-flipped-N.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/recycler/recycler-flipped-N-",
            },
        },
        {
            match = "__recycler__/graphics/entity/recycler/recycler-flipped-S.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/recycler/recycler-flipped-S-",
            },
        },
        {
            match = "__recycler__/graphics/entity/recycler/recycler-flipped-W.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/recycler/recycler-flipped-W-",
            },
        },
    },
    ["rocket-silo"] = {
        {
            match = "__base__/graphics/entity/rocket-silo/06-rocket-silo.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/rocket-silo/06-rocket-silo-",
            },
        },
        {
            match = "__base__/graphics/entity/rocket-silo/14-rocket-silo-front.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/rocket-silo/14-rocket-silo-front-",
            },
        },
    },
    ["thruster"] = {
        {
            match = "__space-age__/graphics/entity/thruster/thruster-1.png",
            overlays = {
                "__5dim_space_age__/graphics/tier-overlay/thruster/thruster-1-",
                "__5dim_space_age__/graphics/tier-overlay/thruster/thruster-2-",
            },
        },
    },
}
