-- Generated by mods/scripts/make-region-overlays.py -- do not edit by hand.
--
-- Maps each vanilla sprite layer to the per-tier recolour overlays that go
-- on top of it.  Same shape as the 5dim_space_age manifest: `match` is the
-- layer's filename and `overlays` the prefix of its ten tier files.
return {
    ["assembling-machine"] = {
        {
            match = "__base__/graphics/entity/assembling-machine-1/assembling-machine-1-base.png",
            overlays = {
                "__5dim_automation__/graphics/tier-overlay/assembling-machine/assembling-machine-1-base-",
            },
        },
        {
            match = "__base__/graphics/entity/assembling-machine-2/assembling-machine-2-base.png",
            overlays = {
                "__5dim_automation__/graphics/tier-overlay/assembling-machine/assembling-machine-2-base-",
            },
        },
        {
            match = "__base__/graphics/entity/assembling-machine-3/assembling-machine-3-base.png",
            overlays = {
                "__5dim_automation__/graphics/tier-overlay/assembling-machine/assembling-machine-3-base-",
            },
        },
    },
    ["oil-refinery"] = {
        {
            match = "__base__/graphics/entity/oil-refinery/east/oil-refinery-east.png",
            overlays = {
                "__5dim_automation__/graphics/tier-overlay/oil-refinery/oil-refinery-east-",
            },
        },
        {
            match = "__base__/graphics/entity/oil-refinery/north/oil-refinery-north.png",
            overlays = {
                "__5dim_automation__/graphics/tier-overlay/oil-refinery/oil-refinery-north-",
            },
        },
        {
            match = "__base__/graphics/entity/oil-refinery/south/oil-refinery-south.png",
            overlays = {
                "__5dim_automation__/graphics/tier-overlay/oil-refinery/oil-refinery-south-",
            },
        },
        {
            match = "__base__/graphics/entity/oil-refinery/west/oil-refinery-west.png",
            overlays = {
                "__5dim_automation__/graphics/tier-overlay/oil-refinery/oil-refinery-west-",
            },
        },
    },
}
