data.raw["accumulator"]["accumulator"].fast_replaceable_group = "accumulator"
data.raw["solar-panel"]["solar-panel"].fast_replaceable_group = "solar-panel"
data.raw["boiler"]["boiler"].fast_replaceable_group = "boiler"
data.raw["generator"]["steam-engine"].fast_replaceable_group = "steam-engine"
data.raw["lamp"]["small-lamp"].fast_replaceable_group = "lamp"
data.raw["electric-pole"]["medium-electric-pole"].fast_replaceable_group = "medium-electric-pole"
data.raw["electric-pole"]["big-electric-pole"].fast_replaceable_group = "big-electric-pole"
data.raw["electric-pole"]["substation"].fast_replaceable_group = "substation"
