--Armor
data.raw.armor["light-armor"].subgroup = "armor-armor"
data.raw.armor["light-armor"].order = "a"
data.raw.armor["heavy-armor"].subgroup = "armor-armor"
data.raw.armor["heavy-armor"].order = "b"
data.raw.armor["modular-armor"].subgroup = "armor-armor"
data.raw.armor["modular-armor"].order = "c"
data.raw.armor["power-armor"].subgroup = "armor-power-armor"
data.raw.armor["power-armor"].order = "a"
data.raw.armor["power-armor-mk2"].subgroup = "armor-power-armor"
data.raw.armor["power-armor-mk2"].order = "b"
data.raw.item["solar-panel-equipment"].subgroup = "armor-solar"
data.raw.item["solar-panel-equipment"].order = "a"
data.raw.item["fission-reactor-equipment"].subgroup = "armor-fision-reactor"
data.raw.item["fission-reactor-equipment"].order = "a"
data.raw.item["battery-equipment"].subgroup = "armor-baterry"
data.raw.item["battery-equipment"].order = "a"
data.raw.item["battery-mk2-equipment"].subgroup = "armor-baterry"
data.raw.item["battery-mk2-equipment"].order = "b"
data.raw.item["exoskeleton-equipment"].subgroup = "armor-exoesqueleto"
data.raw.item["exoskeleton-equipment"].order = "a"
data.raw.item["personal-roboport-equipment"].subgroup = "armor-roboport"
data.raw.item["personal-roboport-equipment"].order = "a"
data.raw.item["personal-roboport-mk2-equipment"].subgroup = "armor-roboport"
data.raw.item["personal-roboport-mk2-equipment"].order = "b"
data.raw.item["night-vision-equipment"].subgroup = "armor-util"
data.raw.item["night-vision-equipment"].order = "d"
data.raw.item["belt-immunity-equipment"].subgroup = "armor-util"
data.raw.item["belt-immunity-equipment"].order = "a"
data.raw.item["energy-shield-equipment"].subgroup = "armor-shield"
data.raw.item["energy-shield-equipment"].order = "a"
data.raw.item["energy-shield-mk2-equipment"].subgroup = "armor-shield"
data.raw.item["energy-shield-mk2-equipment"].order = "b"
data.raw.item["personal-laser-defense-equipment"].subgroup = "armor-laser"
data.raw.item["personal-laser-defense-equipment"].order = "a"
data.raw.item["discharge-defense-equipment"].subgroup = "armor-util"
data.raw.item["discharge-defense-equipment"].order = "b"
data.raw.capsule["discharge-defense-remote"].subgroup = "armor-util"
data.raw.capsule["discharge-defense-remote"].order = "c"

if mods["space-age"] then
    data.raw.armor["mech-armor"].subgroup = "armor-mech-armor"
    data.raw.armor["mech-armor"].order = "a"
    if mods["5dim_equipment"] then
        data.raw.item["battery-mk3-equipment"].subgroup = "armor-armor"
        data.raw.item["battery-mk3-equipment"].order = "d"
    else
        data.raw.item["battery-mk3-equipment"].subgroup = "armor-baterry"
        data.raw.item["battery-mk3-equipment"].order = "c"
    end
    data.raw.item["fusion-reactor-equipment"].subgroup = "armor-reactor"
    data.raw.item["fusion-reactor-equipment"].order = "a"
    data.raw.item["toolbelt-equipment"].subgroup = "armor-util"
    data.raw.item["toolbelt-equipment"].order = "d"
end

-- Automatization
data.raw.item["inserter"].subgroup = "transport-inserter"
data.raw.item["inserter"].order = "a"
data.raw.item["long-handed-inserter"].subgroup = "transport-misc"
data.raw.item["long-handed-inserter"].order = "b"
data.raw.item["fast-inserter"].subgroup = "transport-inserter"
data.raw.item["fast-inserter"].order = "b"
data.raw.item["burner-inserter"].subgroup = "transport-misc"
data.raw.item["burner-inserter"].order = "a"
data.raw.item["bulk-inserter"].subgroup = "transport-bulk-inserter"
data.raw.item["bulk-inserter"].order = "a"
data.raw.item["assembling-machine-1"].subgroup = "assembling-machine"
data.raw.item["assembling-machine-1"].order = "a"
data.raw.item["assembling-machine-2"].subgroup = "assembling-machine"
data.raw.item["assembling-machine-2"].order = "b"
data.raw.item["assembling-machine-3"].subgroup = "assembling-machine"
data.raw.item["assembling-machine-3"].order = "c"

if mods["space-age"] then
    data.raw.item["stack-inserter"].subgroup = "transport-stack-inserter"
    data.raw.item["stack-inserter"].order = "a"
end

--Defense
data.raw.item["laser-turret"].subgroup = "defense-laser-turret"
data.raw.item["laser-turret"].order = "a"
data.raw.item["gun-turret"].subgroup = "defense-gun-turret"
data.raw.item["gun-turret"].order = "a"
data.raw.item["flamethrower-turret"].subgroup = "defense-flame"
data.raw.item["flamethrower-turret"].order = "a"
data.raw.item["artillery-turret"].subgroup = "defense-artillery"
data.raw.item["artillery-turret"].order = "a"
data.raw.ammo["artillery-shell"].subgroup = "defense-artillery"
data.raw.ammo["artillery-shell"].order = "b"
data.raw.capsule["artillery-targeting-remote"].subgroup = "defense-artillery"
data.raw.capsule["artillery-targeting-remote"].order = "c"
data.raw.item["stone-wall"].subgroup = "defense-wall"
data.raw.item["stone-wall"].order = "a"
data.raw.item["gate"].subgroup = "defense-gate"
data.raw.item["gate"].order = "a"
data.raw.item["radar"].subgroup = "defense-radar"
data.raw.item["radar"].order = "a"

if mods["space-age"] then
    data.raw.item["tesla-turret"].subgroup = "defense-tesla"
    data.raw.item["tesla-turret"].order = "a"
    data.raw.item["railgun-turret"].subgroup = "defense-railgun-turret"
    data.raw.item["railgun-turret"].order = "a"
    data.raw.item["rocket-turret"].subgroup = "defense-rocket-turret"
    data.raw.item["rocket-turret"].order = "a"
end

--Decoration
data.raw.item["stone-brick"].subgroup = "decoration-floor"
data.raw.item["stone-brick"].order = "a-a"
data.raw.item["concrete"].subgroup = "decoration-floor"
data.raw.item["concrete"].order = "a-b"
data.raw.item["refined-concrete"].subgroup = "decoration-floor"
data.raw.item["refined-concrete"].order = "a-ba"
data.raw.item["hazard-concrete"].subgroup = "decoration-floor"
data.raw.item["hazard-concrete"].order = "a-bb"
data.raw.item["refined-hazard-concrete"].subgroup = "decoration-floor"
data.raw.item["refined-hazard-concrete"].order = "a-bc"
data.raw.capsule["cliff-explosives"].subgroup = "decoration-floor"
data.raw.capsule["cliff-explosives"].order = "a-aa"
data.raw.item["landfill"].subgroup = "decoration-landfill"
data.raw.item["landfill"].order = "a"

if mods["space-age"] then
    data.raw.item["artificial-yumako-soil"].subgroup = "decoration-landfill"
    data.raw.item["artificial-yumako-soil"].order = "b"
    data.raw.item["overgrowth-yumako-soil"].subgroup = "decoration-landfill"
    data.raw.item["overgrowth-yumako-soil"].order = "c"
    data.raw.item["artificial-jellynut-soil"].subgroup = "decoration-landfill"
    data.raw.item["artificial-jellynut-soil"].order = "d"
    data.raw.item["overgrowth-jellynut-soil"].subgroup = "decoration-landfill"
    data.raw.item["overgrowth-jellynut-soil"].order = "e"
    data.raw.item["ice-platform"].subgroup = "decoration-landfill"
    data.raw.item["ice-platform"].order = "f"
    data.raw.item["foundation"].subgroup = "decoration-landfill"
    data.raw.item["foundation"].order = "g"
end

--Equipment
data.raw.gun["flamethrower"].subgroup = "equipment-flame"
data.raw.gun["flamethrower"].order = "a"
data.raw.item["land-mine"].subgroup = "equipment-capsule"
data.raw.item["land-mine"].order = "ac"
data.raw.gun["rocket-launcher"].subgroup = "equipment-rocket"
data.raw.gun["rocket-launcher"].order = "a"
data.raw.gun["shotgun"].subgroup = "equipment-shotgun"
data.raw.gun["shotgun"].order = "a"
data.raw.gun["combat-shotgun"].subgroup = "equipment-shotgun"
data.raw.gun["combat-shotgun"].order = "b"
data.raw.gun["submachine-gun"].subgroup = "equipment-bullet"
data.raw.gun["submachine-gun"].order = "b"
data.raw.gun["pistol"].subgroup = "equipment-bullet"
data.raw.gun["pistol"].order = "a"
data.raw.ammo["piercing-rounds-magazine"].subgroup = "equipment-bullet"
data.raw.ammo["piercing-rounds-magazine"].order = "d"
data.raw.ammo["firearm-magazine"].subgroup = "equipment-bullet"
data.raw.ammo["firearm-magazine"].order = "c"
data.raw.ammo["flamethrower-ammo"].subgroup = "equipment-flame"
data.raw.ammo["flamethrower-ammo"].order = "b"
data.raw.ammo["explosive-rocket"].subgroup = "equipment-rocket"
data.raw.ammo["explosive-rocket"].order = "c"
data.raw.ammo["rocket"].subgroup = "equipment-rocket"
data.raw.ammo["rocket"].order = "b"
data.raw.ammo["piercing-shotgun-shell"].subgroup = "equipment-shotgun"
data.raw.ammo["piercing-shotgun-shell"].order = "d"
data.raw.ammo["shotgun-shell"].subgroup = "equipment-shotgun"
data.raw.ammo["shotgun-shell"].order = "c"
data.raw.capsule["grenade"].subgroup = "equipment-capsule"
data.raw.capsule["grenade"].order = "a"
data.raw.capsule["cluster-grenade"].subgroup = "equipment-capsule"
data.raw.capsule["cluster-grenade"].order = "ab"
data.raw.capsule["poison-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["poison-capsule"].order = "b"
data.raw.capsule["slowdown-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["slowdown-capsule"].order = "c"
data.raw.capsule["defender-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["defender-capsule"].order = "d"
data.raw.capsule["distractor-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["distractor-capsule"].order = "e"
data.raw.capsule["destroyer-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["destroyer-capsule"].order = "f"
data.raw.ammo["uranium-rounds-magazine"].subgroup = "equipment-bullet"
data.raw.ammo["uranium-rounds-magazine"].order = "e"
data.raw.ammo["atomic-bomb"].subgroup = "equipment-rocket"
data.raw.ammo["atomic-bomb"].order = "d"

if mods["space-age"] then
    data.raw.gun["railgun"].subgroup = "equipment-railgun"
    data.raw.gun["railgun"].order = "a"
    data.raw.ammo["railgun-ammo"].subgroup = "equipment-railgun"
    data.raw.ammo["railgun-ammo"].order = "b"
    data.raw.gun["teslagun"].subgroup = "equipment-teslagun"
    data.raw.gun["teslagun"].order = "a"
    data.raw.ammo["tesla-ammo"].subgroup = "equipment-teslagun"
    data.raw.ammo["tesla-ammo"].order = "b"
    data.raw.ammo["capture-robot-rocket"].subgroup = "equipment-rocket"
    data.raw.ammo["capture-robot-rocket"].order = "e"
end

--Energy
data.raw.item["big-electric-pole"].subgroup = "energy-big"
data.raw.item["big-electric-pole"].order = "a"
data.raw.item["medium-electric-pole"].subgroup = "energy-medium"
data.raw.item["medium-electric-pole"].order = "a"
data.raw.item["small-electric-pole"].subgroup = "energy-pole"
data.raw.item["small-electric-pole"].order = "a"
data.raw.item["solar-panel"].subgroup = "energy-solar-panel"
data.raw.item["solar-panel"].order = "a"
data.raw.item["accumulator"].subgroup = "energy-accumulator"
data.raw.item["accumulator"].order = "a"
data.raw.item["boiler"].subgroup = "energy-boiler"
data.raw.item["boiler"].order = "a"
data.raw.item["steam-engine"].subgroup = "energy-engine-1"
data.raw.item["steam-engine"].order = "a"
data.raw.item["small-lamp"].subgroup = "energy-lamp"
data.raw.item["small-lamp"].order = "a"
data.raw.item["offshore-pump"].subgroup = "liquid-offshore-pump"
data.raw.item["offshore-pump"].order = "a"
data.raw.item["pump"].subgroup = "liquid-small-pump"
data.raw.item["pump"].order = "a"
data.raw.item["substation"].subgroup = "energy-substation"
data.raw.item["substation"].order = "a"

--Intermediate
data.raw.item["iron-stick"].subgroup = "intermediate-misc"
data.raw.item["iron-stick"].order = "a"
data.raw.item["engine-unit"].subgroup = "intermediate-misc"
data.raw.item["engine-unit"].order = "b"
data.raw.item["electric-engine-unit"].subgroup = "intermediate-misc"
data.raw.item["electric-engine-unit"].order = "c"
data.raw.item["explosives"].subgroup = "intermediate-misc"
data.raw.item["explosives"].order = "f"
data.raw.item["battery"].subgroup = "intermediate-misc"
data.raw.item["battery"].order = "e"
data.raw.item["flying-robot-frame"].subgroup = "intermediate-misc"
data.raw.item["flying-robot-frame"].order = "d"
data.raw.tool["automation-science-pack"].subgroup = "intermediate-lab"
data.raw.tool["logistic-science-pack"].subgroup = "intermediate-lab"
data.raw.tool["chemical-science-pack"].subgroup = "intermediate-lab"
data.raw.tool["military-science-pack"].subgroup = "intermediate-lab"
data.raw.tool["production-science-pack"].subgroup = "intermediate-lab"
data.raw.tool["utility-science-pack"].subgroup = "intermediate-lab"
data.raw.tool["space-science-pack"].subgroup = "intermediate-lab"
data.raw.item["electronic-circuit"].subgroup = "intermediate-chip"
data.raw.item["electronic-circuit"].order = "a"
data.raw.item["advanced-circuit"].subgroup = "intermediate-chip"
data.raw.item["advanced-circuit"].order = "b"
data.raw.item["processing-unit"].subgroup = "intermediate-chip"
data.raw.item["processing-unit"].order = "c"
data.raw.item["copper-cable"].subgroup = "intermediate-gear"
data.raw.item["copper-cable"].order = "a"
data.raw.item["iron-gear-wheel"].subgroup = "intermediate-gear"
data.raw.item["iron-gear-wheel"].order = "b"
data.raw.item["low-density-structure"].subgroup = "intermediate-silo"
data.raw.item["low-density-structure"].order = "y"
data.raw.item["rocket-fuel"].subgroup = "intermediate-silo"
data.raw.item["rocket-fuel"].order = "x"
data.raw.item["rocket-part"].subgroup = "intermediate-silo"
data.raw.item["rocket-part"].order = "z"
data.raw.item["rocket-silo"].subgroup = "intermediate-silo"
data.raw.item["rocket-silo"].order = "a"
if not mods["space-age"] then
    data.raw.item["satellite"].subgroup = "intermediate-silo"
    data.raw.item["satellite"].order = "y"
end
data.raw.item["cargo-landing-pad"].subgroup = "intermediate-silo"
data.raw.item["cargo-landing-pad"].order = "b"

if mods["space-age"] then
    data.raw.tool["metallurgic-science-pack"].subgroup = "intermediate-lab-space"
    data.raw.tool["electromagnetic-science-pack"].subgroup = "intermediate-lab-space"
    data.raw.tool["agricultural-science-pack"].subgroup = "intermediate-lab-space"
    data.raw.tool["cryogenic-science-pack"].subgroup = "intermediate-lab-space"
    data.raw.tool["promethium-science-pack"].subgroup = "intermediate-lab-space"
    data.raw.recipe["agricultural-science-pack"].subgroup = "intermediate-lab-space"
end

--Liquids
data.raw.item["chemical-plant"].subgroup = "liquid-plant"
data.raw.item["chemical-plant"].order = "a"
data.raw.item["oil-refinery"].subgroup = "liquid-refinery"
data.raw.item["oil-refinery"].order = "a"
data.raw.item["pumpjack"].subgroup = "liquid-pump"
data.raw.item["pumpjack"].order = "a"
data.raw.item["storage-tank"].subgroup = "liquid-store"
data.raw.item["storage-tank"].order = "a"
data.raw.recipe["sulfuric-acid"].subgroup = "liquid-recipe"
data.raw.recipe["basic-oil-processing"].subgroup = "liquid-recipe"
data.raw.recipe["advanced-oil-processing"].subgroup = "liquid-recipe"
data.raw.recipe["heavy-oil-cracking"].subgroup = "liquid-recipe"
data.raw.recipe["light-oil-cracking"].subgroup = "liquid-recipe"
data.raw.recipe["sulfuric-acid"].subgroup = "liquid-recipe"
data.raw.recipe["solid-fuel-from-light-oil"].subgroup = "liquid-recipe"
data.raw.recipe["solid-fuel-from-petroleum-gas"].subgroup = "liquid-recipe"
data.raw.recipe["solid-fuel-from-heavy-oil"].subgroup = "liquid-recipe"
data.raw.recipe["lubricant"].subgroup = "liquid-recipe"
data.raw.recipe["coal-liquefaction"].subgroup = "liquid-recipe"
data.raw.recipe["barrel"].subgroup = "liquid-item"
data.raw.item["barrel"].subgroup = "liquid-item"

-- Barreling
for _, fluid in pairs(data.raw.fluid) do
    local barrel = fluid.name .. "-barrel"
    local fill = fluid.name .. "-barrel"
    local empty = "empty-" .. fluid.name .. "-barrel"
    if data.raw.item[barrel] then
        data.raw.item[barrel].subgroup = "liquid-item"
    end
    if data.raw.recipe[fill] then
        data.raw.recipe[fill].subgroup = "liquid-fill"
    end
    if data.raw.recipe[empty] then
        data.raw.recipe[empty].subgroup = "liquid-empty"
    end
end


if mods["space-age"] then
    data.raw.recipe["simple-coal-liquefaction"].subgroup = "liquid-recipe"
    data.raw.recipe["acid-neutralisation"].subgroup = "liquid-recipe"
    data.raw.recipe["steam-condensation"].subgroup = "liquid-recipe"
    data.raw.recipe["ice-melting"].subgroup = "liquid-recipe"
end

--Logistic
data.raw.item["logistic-robot"].subgroup = "logistic-robot"
data.raw.item["logistic-robot"].order = "a"
data.raw.item["construction-robot"].subgroup = "logistic-robot-c"
data.raw.item["construction-robot"].order = "a"
data.raw.item["roboport"].subgroup = "logistic-roboport"
data.raw.item["roboport"].order = "a"
data.raw.item["passive-provider-chest"].subgroup = "logistic-pasive"
data.raw.item["passive-provider-chest"].order = "a"
data.raw.item["buffer-chest"].subgroup = "logistic-buffer"
data.raw.item["buffer-chest"].order = "a"
data.raw.item["active-provider-chest"].subgroup = "logistic-active"
data.raw.item["active-provider-chest"].order = "a"
data.raw.item["storage-chest"].subgroup = "logistic-storage"
data.raw.item["storage-chest"].order = "a"
data.raw.item["requester-chest"].subgroup = "logistic-requester"
data.raw.item["requester-chest"].order = "a"
data.raw.item["red-wire"].subgroup = "logistic-wire"
data.raw.item["red-wire"].order = "b"
data.raw.item["green-wire"].subgroup = "logistic-wire"
data.raw.item["green-wire"].order = "c"
data.raw.item["beacon"].subgroup = "beacon"
data.raw.item["beacon"].order = "a"
data.raw.item["arithmetic-combinator"].subgroup = "logistic-comb"
data.raw.item["arithmetic-combinator"].order = "a"
data.raw.item["decider-combinator"].subgroup = "logistic-comb"
data.raw.item["decider-combinator"].order = "b"
data.raw.item["constant-combinator"].subgroup = "logistic-comb"
data.raw.item["constant-combinator"].order = "c"
data.raw.item["selector-combinator"].subgroup = "logistic-comb"
data.raw.item["selector-combinator"].order = "d"
data.raw.item["display-panel"].subgroup = "logistic-comb"
data.raw.item["display-panel"].order = "e"
data.raw["upgrade-item"]["upgrade-planner"].subgroup = "logistic-plan"
data.raw["upgrade-item"]["upgrade-planner"].order = "c"
data.raw["deconstruction-item"]["deconstruction-planner"].subgroup = "logistic-plan"
data.raw["deconstruction-item"]["deconstruction-planner"].order = "c"
data.raw["blueprint"]["blueprint"].subgroup = "logistic-plan"
data.raw["blueprint"]["blueprint"].order = "b"
data.raw["blueprint-book"]["blueprint-book"].subgroup = "logistic-plan"
data.raw["blueprint-book"]["blueprint-book"].order = "a"
data.raw.item["power-switch"].subgroup = "logistic-comb"
data.raw.item["power-switch"].order = "d"
data.raw.item["programmable-speaker"].subgroup = "logistic-comb"
data.raw.item["programmable-speaker"].order = "d"

--Mining
data.raw.item["electric-mining-drill"].subgroup = "mining-speed"
data.raw.item["electric-mining-drill"].order = "a"
data.raw.item["burner-mining-drill"].subgroup = "mining-range"
data.raw.item["burner-mining-drill"].order = "a"
data.raw["repair-tool"]["repair-pack"].subgroup = "repair"
data.raw["repair-tool"]["repair-pack"].order = "a"
data.raw.item["lab"].subgroup = "lab"
data.raw.item["lab"].order = "a"

if mods["quality"] and not mods["space-age"] then
    data.raw.item["recycler"].subgroup = "mining-recycler"
    data.raw.item["recycler"].order = "a"
end
if mods["space-age"] then
    data.raw.item["recycler"].subgroup = "fulgora-recycler"
    data.raw.item["recycler"].order = "a"
    data.raw.item["biolab"].subgroup = "biolab"
    data.raw.item["biolab"].order = "a"
end

--Module
data.raw.module["speed-module"].subgroup = "speed"
data.raw.module["speed-module"].order = "a"
data.raw.module["speed-module-2"].subgroup = "speed"
data.raw.module["speed-module-2"].order = "b"
data.raw.module["speed-module-3"].subgroup = "speed"
data.raw.module["speed-module-3"].order = "c"
data.raw.module["productivity-module"].subgroup = "productivity"
data.raw.module["productivity-module"].order = "a"
data.raw.module["productivity-module-2"].subgroup = "productivity"
data.raw.module["productivity-module-2"].order = "b"
data.raw.module["productivity-module-3"].subgroup = "productivity"
data.raw.module["productivity-module-3"].order = "c"
data.raw.module["efficiency-module"].subgroup = "efficiency"
data.raw.module["efficiency-module"].order = "a"
data.raw.module["efficiency-module-2"].subgroup = "efficiency"
data.raw.module["efficiency-module-2"].order = "b"
data.raw.module["efficiency-module-3"].subgroup = "efficiency"
data.raw.module["efficiency-module-3"].order = "c"

if mods["quality"] then
    data.raw.module["quality-module"].subgroup = "quality"
    data.raw.module["quality-module"].order = "a"
    data.raw.module["quality-module-2"].subgroup = "quality"
    data.raw.module["quality-module-2"].order = "b"
    data.raw.module["quality-module-3"].subgroup = "quality"
    data.raw.module["quality-module-3"].order = "c"
end

--Resources
data.raw.item["stone-furnace"].subgroup = "furnace-coal"
data.raw.item["stone-furnace"].order = "a"
data.raw.item["steel-furnace"].subgroup = "furnace-coal"
data.raw.item["steel-furnace"].order = "b"
data.raw.item["electric-furnace"].subgroup = "furnace-electric"
data.raw.item["electric-furnace"].order = "a"

--Plates
data.raw.item["iron-plate"].subgroup = "plates-plates"
data.raw.item["iron-plate"].order = "aa"
data.raw.item["copper-plate"].subgroup = "plates-plates"
data.raw.item["copper-plate"].order = "ab"
data.raw.item["uranium-235"].subgroup = "plates-plates"
data.raw.item["uranium-235"].order = "y"
data.raw.item["uranium-238"].subgroup = "plates-plates"
data.raw.item["uranium-238"].order = "z"
data.raw.item["steel-plate"].subgroup = "plates-misc"
data.raw.item["steel-plate"].order = "a"
data.raw.item["sulfur"].subgroup = "plates-misc"
data.raw.item["sulfur"].order = "c"
data.raw.item["plastic-bar"].subgroup = "plates-misc"
data.raw.item["plastic-bar"].order = "b"
data.raw.item["wood"].subgroup = "plates-misc"
data.raw.item["coal"].subgroup = "plates-fuel"
data.raw.item["coal"].order = "b"
data.raw.item["solid-fuel"].subgroup = "plates-fuel"
data.raw.item["solid-fuel"].order = "c"
data.raw.item["nuclear-fuel"].subgroup = "plates-fuel"
data.raw.item["nuclear-fuel"].order = "d"
data.raw.recipe["nuclear-fuel"].subgroup = "plates-fuel"
data.raw.recipe["nuclear-fuel"].order = "d"
data.raw.item["iron-ore"].subgroup = "plates-ore"
data.raw.item["iron-ore"].order = "a"
data.raw.item["copper-ore"].subgroup = "plates-ore"
data.raw.item["copper-ore"].order = "b"
data.raw.item["stone"].subgroup = "plates-ore"
data.raw.item["stone"].order = "c"
data.raw.item["uranium-ore"].subgroup = "plates-ore"
data.raw.item["uranium-ore"].order = "d"
data.raw.capsule["raw-fish"].subgroup = "plates-ore"
data.raw.capsule["raw-fish"].order = "e"

--Trains
data.raw["rail-planner"]["rail"].subgroup = "trains-rails"
data.raw["rail-planner"]["rail"].order = "a"
data.raw.item["train-stop"].subgroup = "trains-rails"
data.raw.item["train-stop"].order = "d"
data.raw.item["rail-signal"].subgroup = "trains-rails"
data.raw.item["rail-signal"].order = "e"
data.raw.item["rail-chain-signal"].subgroup = "trains-rails"
data.raw.item["rail-chain-signal"].order = "f"
data.raw["item-with-entity-data"]["locomotive"].subgroup = "trains-locomotive"
data.raw["item-with-entity-data"]["locomotive"].order = "a"
data.raw["item-with-entity-data"]["cargo-wagon"].subgroup = "trains-wagons"
data.raw["item-with-entity-data"]["cargo-wagon"].order = "a"
data.raw["item-with-entity-data"]["fluid-wagon"].subgroup = "trains-liquids"
data.raw["item-with-entity-data"]["fluid-wagon"].order = "a"
data.raw["item-with-entity-data"]["artillery-wagon"].subgroup = "trains-artillery"
data.raw["item-with-entity-data"]["artillery-wagon"].order = "a"

if mods["elevated-rails"] then
    data.raw["rail-planner"]["rail-ramp"].subgroup = "trains-rails"
    data.raw["rail-planner"]["rail-ramp"].order = "b"
    data.raw.item["rail-support"].subgroup = "trains-rails"
    data.raw.item["rail-support"].order = "c"
end

--Nuclear
data.raw.item["steam-turbine"].subgroup = "nuclear-turbine"
data.raw.item["steam-turbine"].order = "a"
data.raw.item["heat-exchanger"].subgroup = "nuclear-heat"
data.raw.item["heat-exchanger"].order = "a"
data.raw.item["nuclear-reactor"].subgroup = "nuclear-reactor"
data.raw.item["nuclear-reactor"].order = "a"
data.raw.item["heat-pipe"].subgroup = "nuclear-pipe"
data.raw.item["heat-pipe"].order = "a"
data.raw.item["centrifuge"].subgroup = "nuclear-centri"
data.raw.item["centrifuge"].order = "a"
data.raw.item["uranium-fuel-cell"].subgroup = "nuclear-item"
data.raw.item["uranium-fuel-cell"].order = "a"
data.raw.item["depleted-uranium-fuel-cell"].subgroup = "nuclear-item"
data.raw.item["depleted-uranium-fuel-cell"].order = "b"
data.raw.recipe["uranium-processing"].subgroup = "nuclear-recipe"
data.raw.recipe["uranium-processing"].order = "a"
data.raw.recipe["uranium-fuel-cell"].subgroup = "nuclear-recipe"
data.raw.recipe["uranium-fuel-cell"].order = "b"
data.raw.recipe["nuclear-fuel-reprocessing"].subgroup = "nuclear-recipe"
data.raw.recipe["nuclear-fuel-reprocessing"].order = "c"
data.raw.recipe["kovarex-enrichment-process"].subgroup = "nuclear-recipe"
data.raw.recipe["kovarex-enrichment-process"].order = "d"

if mods["space-age"] then
    data.raw.item["fusion-reactor"].subgroup = "nuclear-fusion-reactor"
    data.raw.item["fusion-reactor"].order = "a"
    data.raw.item["fusion-generator"].subgroup = "nuclear-fusion-generator"
    data.raw.item["fusion-generator"].order = "a"
end

--Transport
data.raw.item["loader"].subgroup = "transport-loader"
data.raw.item["loader"].order = "a"
data.raw.item["fast-loader"].subgroup = "transport-loader"
data.raw.item["fast-loader"].order = "b"
data.raw.item["express-loader"].subgroup = "transport-loader"
data.raw.item["express-loader"].order = "c"
data.raw.item["splitter"].subgroup = "transport-splitters"
data.raw.item["splitter"].order = "a"
data.raw.item["fast-splitter"].subgroup = "transport-splitters"
data.raw.item["fast-splitter"].order = "b"
data.raw.item["express-splitter"].subgroup = "transport-splitters"
data.raw.item["express-splitter"].order = "c"
data.raw.item["transport-belt"].subgroup = "transport-belt"
data.raw.item["transport-belt"].order = "a"
data.raw.item["fast-transport-belt"].subgroup = "transport-belt"
data.raw.item["fast-transport-belt"].order = "b"
data.raw.item["express-transport-belt"].subgroup = "transport-belt"
data.raw.item["express-transport-belt"].order = "c"
data.raw.item["underground-belt"].subgroup = "transport-ground"
data.raw.item["underground-belt"].order = "a"
data.raw.item["fast-underground-belt"].subgroup = "transport-ground"
data.raw.item["fast-underground-belt"].order = "b"
data.raw.item["express-underground-belt"].subgroup = "transport-ground"
data.raw.item["express-underground-belt"].order = "c"
data.raw.item["pipe"].subgroup = "transport-pipe"
data.raw.item["pipe"].order = "a"
data.raw.item["pipe-to-ground"].subgroup = "transport-pipe-ground"
data.raw.item["pipe-to-ground"].order = "a"
data.raw.item["wooden-chest"].subgroup = "store-solid"
data.raw.item["wooden-chest"].order = "a"
data.raw.item["iron-chest"].subgroup = "store-solid"
data.raw.item["iron-chest"].order = "b"
data.raw.item["steel-chest"].subgroup = "store-solid"
data.raw.item["steel-chest"].order = "c"

if mods["space-age"] then
    if mods["5dim_transport"] then
        data.raw.item["turbo-loader"].subgroup = "transport-turbo-belt"
        data.raw.item["turbo-loader"].order = "d"
        data.raw.item["turbo-splitter"].subgroup = "transport-turbo-belt"
        data.raw.item["turbo-splitter"].order = "c"
        data.raw.item["turbo-transport-belt"].subgroup = "transport-turbo-belt"
        data.raw.item["turbo-transport-belt"].order = "a"
        data.raw.item["turbo-underground-belt"].subgroup = "transport-turbo-belt"
        data.raw.item["turbo-underground-belt"].order = "b"
    else
        data.raw.item["turbo-loader"].subgroup = "transport-loader"
        data.raw.item["turbo-loader"].order = "d"
        data.raw.item["turbo-splitter"].subgroup = "transport-splitters"
        data.raw.item["turbo-splitter"].order = "d"
        data.raw.item["turbo-transport-belt"].subgroup = "transport-belt"
        data.raw.item["turbo-transport-belt"].order = "d"
        data.raw.item["turbo-underground-belt"].subgroup = "transport-ground"
        data.raw.item["turbo-underground-belt"].order = "d"
    end
    data.raw.recipe["casting-pipe"].subgroup = "transport-pipe"
    data.raw.recipe["casting-pipe"].order = "b"
    data.raw.recipe["casting-pipe-to-ground"].subgroup = "transport-pipe-ground"
    data.raw.recipe["casting-pipe-to-ground"].order = "b"
end

--Vehicles
data.raw["item-with-entity-data"]["tank"].subgroup = "vehicles-tank"
data.raw["item-with-entity-data"]["tank"].order = "a"
data.raw["item-with-entity-data"]["car"].subgroup = "vehicles-car"
data.raw["item-with-entity-data"]["car"].order = "a"
data.raw.ammo["cannon-shell"].subgroup = "vehicles-tank"
data.raw.ammo["cannon-shell"].order = "w"
data.raw.ammo["explosive-cannon-shell"].subgroup = "vehicles-tank"
data.raw.ammo["explosive-cannon-shell"].order = "x"
data.raw.ammo["uranium-cannon-shell"].subgroup = "vehicles-tank"
data.raw.ammo["uranium-cannon-shell"].order = "y"
data.raw.ammo["explosive-uranium-cannon-shell"].subgroup = "vehicles-tank"
data.raw.ammo["explosive-uranium-cannon-shell"].order = "z"
data.raw["item-with-entity-data"]["spidertron"].subgroup = "vehicles-spider"
data.raw["item-with-entity-data"]["spidertron"].order = "a"
data.raw["spidertron-remote"]["spidertron-remote"].subgroup = "vehicles-spider"
data.raw["spidertron-remote"]["spidertron-remote"].order = "b"


-- Planets
-- Orbit
if mods["space-age"] then
    data.raw.item["space-platform-foundation"].subgroup = "orbit-platform"
    data.raw.item["space-platform-foundation"].order = "a"
    data.raw["space-platform-starter-pack"]["space-platform-starter-pack"].subgroup = "orbit-platform"
    data.raw["space-platform-starter-pack"]["space-platform-starter-pack"].order = "b"
    data.raw.item["cargo-bay"].subgroup = "orbit-platform"
    data.raw.item["cargo-bay"].order = "c"
    data.raw.item["asteroid-collector"].subgroup = "orbit-buildings"
    data.raw.item["asteroid-collector"].order = "d"
    data.raw.item["crusher"].subgroup = "orbit-buildings"
    data.raw.item["crusher"].order = "e"
    data.raw.item["thruster"].subgroup = "orbit-buildings"
    data.raw.item["thruster"].order = "f"
    data.raw.recipe["metallic-asteroid-reprocessing"].subgroup = "orbit-reprocesing"
    data.raw.recipe["carbonic-asteroid-reprocessing"].subgroup = "orbit-reprocesing"
    data.raw.recipe["oxide-asteroid-reprocessing"].subgroup = "orbit-reprocesing"
    data.raw.recipe["metallic-asteroid-crushing"].subgroup = "orbit-crushing"
    data.raw.recipe["carbonic-asteroid-crushing"].subgroup = "orbit-crushing"
    data.raw.recipe["oxide-asteroid-crushing"].subgroup = "orbit-crushing"
    data.raw.recipe["advanced-metallic-asteroid-crushing"].subgroup = "orbit-advanced-crushing"
    data.raw.recipe["advanced-carbonic-asteroid-crushing"].subgroup = "orbit-advanced-crushing"
    data.raw.recipe["advanced-oxide-asteroid-crushing"].subgroup = "orbit-advanced-crushing"
    data.raw.recipe["thruster-fuel"].subgroup = "orbit-liquids"
    data.raw.recipe["thruster-fuel"].order = "a"
    data.raw.recipe["advanced-thruster-fuel"].subgroup = "orbit-liquids"
    data.raw.recipe["advanced-thruster-fuel"].order = "b"
    data.raw.recipe["thruster-oxidizer"].subgroup = "orbit-liquids"
    data.raw.recipe["thruster-oxidizer"].order = "c"
    data.raw.recipe["advanced-thruster-oxidizer"].subgroup = "orbit-liquids"
    data.raw.recipe["advanced-thruster-oxidizer"].order = "d"
    data.raw.item["metallic-asteroid-chunk"].subgroup = "orbit-chunks"
    data.raw.item["metallic-asteroid-chunk"].order = "a"
    data.raw.item["carbonic-asteroid-chunk"].subgroup = "orbit-chunks"
    data.raw.item["carbonic-asteroid-chunk"].order = "b"
    data.raw.item["oxide-asteroid-chunk"].subgroup = "orbit-chunks"
    data.raw.item["oxide-asteroid-chunk"].order = "c"
    data.raw.item["promethium-asteroid-chunk"].subgroup = "orbit-chunks"
    data.raw.item["promethium-asteroid-chunk"].order = "d"
    data.raw.item["carbon"].subgroup = "orbit-resources"
    data.raw.recipe["carbon"].subgroup = "orbit-resources"
    data.raw.item["ice"].subgroup = "orbit-resources"
    data.raw.recipe["coal-synthesis"].subgroup = "orbit-resources"
end

-- Nauvis
if mods["space-age"] then
end

-- Vulcanus
if mods["space-age"] then
    data.raw.item["foundry"].subgroup = "vulcanus-foundry"
    data.raw.item["foundry"].order = "a"
    data.raw.item["big-mining-drill"].subgroup = "vulcanus-mining-big"
    data.raw.item["big-mining-drill"].order = "a"
    data.raw.recipe["molten-iron-from-lava"].subgroup = "vulcanus-metallurgy"
    data.raw.recipe["molten-copper-from-lava"].subgroup = "vulcanus-metallurgy"
    data.raw.recipe["molten-iron"].subgroup = "vulcanus-metallurgy"
    data.raw.recipe["molten-copper"].subgroup = "vulcanus-metallurgy"
    data.raw.recipe["casting-iron"].subgroup = "vulcanus-metallurgy-plates"
    data.raw.recipe["casting-copper"].subgroup = "vulcanus-metallurgy-plates"
    data.raw.recipe["casting-steel"].subgroup = "vulcanus-metallurgy-plates"
    data.raw.recipe["casting-iron-gear-wheel"].subgroup = "vulcanus-metallurgy-items"
    data.raw.recipe["casting-iron-stick"].subgroup = "vulcanus-metallurgy-items"
    data.raw.recipe["casting-pipe"].subgroup = "vulcanus-metallurgy-items"
    data.raw.recipe["casting-pipe-to-ground"].subgroup = "vulcanus-metallurgy-items"
    data.raw.recipe["casting-low-density-structure"].subgroup = "vulcanus-metallurgy-items"
    data.raw.recipe["concrete-from-molten-iron"].subgroup = "vulcanus-metallurgy-items"
    data.raw.recipe["casting-copper-cable"].subgroup = "vulcanus-metallurgy-items"
    data.raw.item["calcite"].subgroup = "vulcanus-metallurgy-tungsten"
    data.raw.item["tungsten-ore"].subgroup = "vulcanus-metallurgy-tungsten"
    data.raw.item["tungsten-plate"].subgroup = "vulcanus-metallurgy-tungsten"
    data.raw.item["tungsten-carbide"].subgroup = "vulcanus-metallurgy-tungsten"
    data.raw.recipe["tungsten-plate"].subgroup = "vulcanus-metallurgy-tungsten"
    data.raw.recipe["tungsten-carbide"].subgroup = "vulcanus-metallurgy-tungsten"
end

-- Fulgora
if mods["space-age"] then
    data.raw.item["electromagnetic-plant"].subgroup = "fulgora-electromagnetic"
    data.raw.item["electromagnetic-plant"].order = "a"
    data.raw.item["lightning-rod"].subgroup = "fulgora-rod"
    data.raw.item["lightning-rod"].order = "a"
    data.raw.item["lightning-collector"].subgroup = "fulgora-collector"
    data.raw.item["lightning-collector"].order = "a"
    data.raw.recipe["scrap-recycling"].subgroup = "fulgora-resources"
    data.raw.recipe["holmium-plate"].subgroup = "fulgora-resources"
    data.raw.item["holmium-plate"].subgroup = "fulgora-resources"
    data.raw.recipe["superconductor"].subgroup = "fulgora-resources"
    data.raw.item["superconductor"].subgroup = "fulgora-resources"
    data.raw.recipe["supercapacitor"].subgroup = "fulgora-resources"
    data.raw.item["supercapacitor"].subgroup = "fulgora-resources"
    data.raw.item["holmium-ore"].subgroup = "fulgora-resources"
    data.raw.item["scrap"].subgroup = "fulgora-resources"
    data.raw.recipe["holmium-solution"].subgroup = "fulgora-liquids"
    data.raw.recipe["electrolyte"].subgroup = "fulgora-liquids"
end

-- Gleba
if mods["space-age"] then
    data.raw.item["agricultural-tower"].subgroup = "gleba-agricultural-tower"
    data.raw.item["agricultural-tower"].order = "a"
    data.raw.item["biochamber"].subgroup = "gleba-biochamber"
    data.raw.item["biochamber"].order = "a"
    data.raw.item["captive-biter-spawner"].subgroup = "gleba-captive"
    data.raw.item["captive-biter-spawner"].order = "a"
    data.raw.recipe["yumako-processing"].subgroup = "gleba-agricultural-processing"
    data.raw.recipe["jellynut-processing"].subgroup = "gleba-agricultural-processing"
    data.raw.recipe["nutrients-from-spoilage"].subgroup = "gleba-nutrient"
    data.raw.recipe["nutrients-from-yumako-mash"].subgroup = "gleba-nutrient"
    data.raw.recipe["nutrients-from-bioflux"].subgroup = "gleba-nutrient"
    data.raw.recipe["copper-bacteria"].subgroup = "gleba-seeds"
    data.raw.recipe["iron-bacteria"].subgroup = "gleba-seeds"
    data.raw.recipe["pentapod-egg"].subgroup = "gleba-seeds"
    data.raw.item["yumako-seed"].subgroup = "gleba-seeds"
    data.raw.item["jellynut-seed"].subgroup = "gleba-seeds"
    data.raw.recipe["copper-bacteria-cultivation"].subgroup = "gleba-cultivation"
    data.raw.recipe["iron-bacteria-cultivation"].subgroup = "gleba-cultivation"
    data.raw.recipe["rocket-fuel-from-jelly"].subgroup = "gleba-items"
    data.raw.recipe["bioflux"].subgroup = "gleba-items"
    data.raw.recipe["bioplastic"].subgroup = "gleba-items"
    data.raw.recipe["biosulfur"].subgroup = "gleba-items"
    data.raw.recipe["carbon-fiber"].subgroup = "gleba-items"
    data.raw.recipe["burnt-spoilage"].subgroup = "gleba-items"
    data.raw.capsule["yumako"].subgroup = "gleba-items"
    data.raw.capsule["jellynut"].subgroup = "gleba-items"
    data.raw.item["copper-bacteria"].subgroup = "gleba-items"
    data.raw.item["iron-bacteria"].subgroup = "gleba-items"
    data.raw.item["spoilage"].subgroup = "gleba-items"
    data.raw.item["nutrients"].subgroup = "gleba-items"
    data.raw.capsule["bioflux"].subgroup = "gleba-items2"
    data.raw.capsule["yumako-mash"].subgroup = "gleba-items2"
    data.raw.capsule["jelly"].subgroup = "gleba-items2"
    data.raw.item["carbon-fiber"].subgroup = "gleba-items2"
    data.raw.item["biter-egg"].subgroup = "gleba-items2"
    data.raw.item["pentapod-egg"].subgroup = "gleba-items2"
    data.raw.recipe["biolubricant"].subgroup = "gleba-liquids"
    data.raw.item["tree-seed"].subgroup = "gleba-nauvis-wood"
    data.raw.recipe["wood-processing"].subgroup = "gleba-nauvis-wood"
    data.raw.recipe["fish-breeding"].subgroup = "gleba-nauvis-wood"
    data.raw.recipe["nutrients-from-fish"].subgroup = "gleba-nauvis-wood"
    data.raw.recipe["nutrients-from-biter-egg"].subgroup = "gleba-nauvis-wood"
end

-- Aquilo
if mods["space-age"] then
    data.raw.item["cryogenic-plant"].subgroup = "aquilo-cryogenic"
    data.raw.item["cryogenic-plant"].order = "a"
    data.raw.item["heating-tower"].subgroup = "aquilo-heating-tower"
    data.raw.item["heating-tower"].order = "a"
    data.raw.recipe["ammoniacal-solution-separation"].subgroup = "aquilo-items"
    data.raw.recipe["solid-fuel-from-ammonia"].subgroup = "aquilo-items"
    data.raw.recipe["ammonia-rocket-fuel"].subgroup = "aquilo-items"
    data.raw.recipe["lithium"].subgroup = "aquilo-items"
    data.raw.item["lithium"].subgroup = "aquilo-items"
    data.raw.recipe["lithium-plate"].subgroup = "aquilo-items"
    data.raw.item["lithium-plate"].subgroup = "aquilo-items"
    data.raw.recipe["quantum-processor"].subgroup = "aquilo-items"
    data.raw.item["quantum-processor"].subgroup = "aquilo-items"
    data.raw.recipe["fusion-power-cell"].subgroup = "aquilo-items"
    data.raw.item["fusion-power-cell"].subgroup = "aquilo-items"
    data.raw.recipe["fluoroketone"].subgroup = "aquilo-liquids"
    data.raw.recipe["fluoroketone-cooling"].subgroup = "aquilo-liquids"
end
